name = "Autocorrelations"
uuid = "c73fd7d7-162c-4687-9dc9-45d4c4ecdd82"
authors = ["Jan Weidner <jw3126@gmail.com> and contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
